spring.application.name=notification-service

server.port=${SERVER_PORT:8083}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP:localhost:9092}
spring.kafka.consumer.group-id=notification-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.mongodb.uri=mongodb://${MONGO_HOST:localhost}:27017/notifications

spring.mail.host=${SMTP_HOST:localhost}
spring.mail.port=${SMTP_PORT:1025}

nexusone.notifications.support-inbox=support-inbox@nexusone.dev
nexusone.notifications.from=noreply@nexusone.dev

spring.rabbitmq.host=${RABBIT_HOST:localhost}
spring.rabbitmq.port=${RABBIT_PORT:5672}

nexusone.notifications.retry-ttl-ms=${NOTIFY_RETRY_TTL_MS:10000}
nexusone.notifications.max-attempts=3

management.endpoints.web.exposure.include=health,prometheus
management.metrics.distribution.percentiles-histogram.http.server.requests=true
