apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: nexusone
spec:
  replicas: 1
  selector:
    matchLabels: { app: gateway }
  template:
    metadata:
      labels: { app: gateway }
    spec:
      containers:
        - name: gateway
          image: nexusone/gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: EUREKA_URI
              value: http://discovery-server:8761/eureka
            - name: REDIS_HOST
              value: redis
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: nexusone
spec:
  selector: { app: gateway }
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
