spring.application.name=gateway

server.port=${SERVER_PORT:8080}

eureka.client.enabled=true
eureka.client.service-url.defaultZone=${EUREKA_URI:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.server.webmvc.routes[0].id=ticket-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://ticket-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/tickets/**,/api/users/**

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=6379

nexusone.ratelimit.window-seconds=60
nexusone.ratelimit.max-requests=20

management.endpoints.web.exposure.include=health,prometheus
management.metrics.distribution.percentiles-histogram.http.server.requests=true
